### ISSUE TITLE
Improve the inefficient code base

### ISSUE THREAD

**Issue by iamareebjamal** [iamareebjamal/get_results#4]
The current code base is very inefficient and non compliant with guidelines. Contributors may want to collaborate with each other to solve the issue together

**Comment by AnubhaAgrawal** [comment]
I want to work on this issue.

**Comment by iamareebjamal** [comment]
Sure

Thanks

**Comment by Sakshisaraswat** [comment]
@AnubhaAgrawal has worked on main.py
i will be sending PR on utilis and enlist

**Comment by iamareebjamal** [comment]
Thanks. I have merged it

**Comment by iamareebjamal** [comment]
Fixed
